services:
  - type: web
    name: springboot-shopapp
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-square-fog-a4nspwnd-pooler.us-east-1.aws.neon.tech/ebook?sslmode=require
